### ISSUE TITLE
Versions not working

### ISSUE THREAD

**Issue by Scottlandish** [jhale1805/power-projectiles#12]
I launched this plugin in my server on vers 1.17.1 and the recipes showed only 3 arrows, and only 2 of them worked (showed teleport, swap, and explosive, and explosive didn't work). I then launched on 1.16.5 and the plugin is not even showing up.

**Comment by thehale** [comment]
@Scottlandish do you see any errors in your server's console? If so, can you post their full contents here?

Also what server software are you running? E.g. Spigot, Paper, Bukkit, etc.

**Comment by Scottlandish** [comment]
There are no errors in the console and I am running spigot

**Comment by thehale** [comment]
And I'm assuming you are using version 1.8.0 of the plugin? 

Have you used version 1.7.1 before? Does that version work for you?

**Comment by Scottlandish** [comment]
I am running vers 1.8.0 of the plugin, and the only vers i've tried that it shows up in is 1.17.1, in 1.16.5 it doesn't show up in the plugin list or work.

**Comment by Scottlandish** [comment]
oh wait I just noticed for 1.7.1 you meant the plugin vers lemme try that real quick

**Comment by thehale** [comment]
Could you include a picture of the plugin list you are referring to, both with 1.17.1 and 1.16.5? I'm not familiar with what you are referring to there...

**Comment by Scottlandish** [comment]
![2021-08-22_16 46 15](https://user-images.githubusercontent.com/89361961/130372628-018c93ee-afd7-46c1-a702-ffe72cf5cdec.png)
<img width="810" alt="plugin ss" src="https://user-images.githubusercontent.com/89361961/130372633-42053295-37ec-49d2-b90b-a257010e51fe.PNG">
yeah it's the same as with plugin version 1.7.1 and 1.8.0

**Comment by thehale** [comment]
It looks like you are in a new world. Has your character gotten the Enchanter advancement yet? If not, that would explain the lack of recipes.

As for the disfunction of the explosive arrow, are you shooting it from a Flame enchanted bow? The idea there is you need something to ignite the TNT tipped on the end of the arrow when shooting it.

**Comment by Scottlandish** [comment]
I did get the enchanter achievement, and the flame bow I didn’t try that makes sense, but why are there only 3 arrows showing up then?

**Comment by Kholdster** [comment]
You have to open recipes from a crafting table in order to see the rest of them, as all the others need a 3x3 grid to create. :)

**Comment by Scottlandish** [comment]
That was 6 months ago

**Comment by thehale** [comment]
I'm catching back up on the issues in this repository. I'm closing this one because it appears to have been resolved. If you disagree, feel free to request that it be re-opened OR create a new bug report with details for Minecraft 1.19.
